server {
    listen 80;

    # 웹사이트의 파일들이 위치하는 기본 폴더를 지정
    root /usr/share/nginx/html;

    # 폴더에 접속했을 때 기본적으로 보여줄 파일을 설정
    index index.html;

    # 모든 요청에 대한 처리 규칙
    location / {
        # 요청된 주소(URI)에 해당하는 파일이나 폴더가 있는지 확인하고,
        # 만약 없다면 모든 요청을 루트의 index.html로 보내줍니다.
        # 이 설정이 없으면 '/about' 같은 주소로 새로고침 시 404 에러가 발생
        try_files $uri $uri/ /index.html;
    }
}